name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v2
      - name: Install dependencis
        uses: |
          npm ci
          npm run client:install
          npm run client:build

      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: mernh #Must be unique in Heroku
          heroku_email: solsarok@gmail.com
